### PR TITLE
add missing car_class_name & car_class_short_name

### PR DESCRIPTION
**Pull request by tobiaszuercher**
these two are missing

### CODE REVIEW

**Comment by AdrianJSClark** [comment]
Thanks for this! Sorry I missed those.

**Comment by tobiaszuercher** [comment]
no apology necessary at all :)

**Comment by tobiaszuercher** [comment]
can you release it to nuget? @AdrianJSClark

**Comment by AdrianJSClark** [comment]
Just need to do some cleaning up of other stuff that is in-flight.

Should get the time to do that this afternoon before the GP. If not, should get it wrapped up on Monday.

**Pull request merged**
